import type { Locale } from "@crm/db/locale";

type Translated = Exclude<Locale, "en">;

const GERMAN = {
	Amount: "Betrag",
	"Amount in reporting currency": "Betrag in Berichtswährung",
	Archived: "Archiviert",
	City: "Stadt",
	Closed: "Abgeschlossen",
	"Closed reason": "Grund für den Abschluss",
	Company: "Firma",
	"Company domain": "Domain der Firma",
	Contacts: "Kontakte",
	Country: "Land",
	Created: "Angelegt",
	Currency: "Währung",
	Domain: "Domain",
	Email: "E-Mail",
	"Expected close": "Erwarteter Abschluss",
	"First name": "Vorname",
	Industry: "Branche",
	"Last activity": "Letzte Aktivität",
	"Last name": "Nachname",
	LinkedIn: "LinkedIn",
	Name: "Name",
	"Open deals": "Offene Geschäfte",
	Owner: "Zuständig",
	"Owner email": "E-Mail der zuständigen Person",
	Persona: "Rolle",
	Phone: "Telefon",
	Potential: "Potenzial",
	"Reporting currency": "Berichtswährung",
	Seniority: "Ebene",
	Source: "Herkunft",
	Stage: "Phase",
	Status: "Status",
	Title: "Position",
	Website: "Website",
	"Demo booked": "Termin vereinbart",
	"Qualified to buy": "Kaufbereit geprüft",
	"Decision maker in": "Entscheider überzeugt",
	"Contract sent": "Vertrag verschickt",
	"Closed won": "Gewonnen",
	"Closed lost": "Verloren",
	Unqualified: "Nicht passend",

	Customer: "Kunde",
	Interested: "Interessiert",
	Watch: "Beobachten",
	High: "Hoch",
	Medium: "Mittel",
	Low: "Niedrig",

	Manual: "Manuell",
	Import: "Import",
	Calendar: "Kalender",
	Tracking: "Tracking",

	companies: "firmen",
	contacts: "kontakte",
	deals: "geschaefte",
} satisfies Record<string, string>;

type ExportKey = keyof typeof GERMAN;

const SPANISH = {
	Amount: "Importe",
	"Amount in reporting currency": "Importe en moneda de referencia",
	Archived: "Archivado",
	City: "Ciudad",
	Closed: "Cerrado",
	"Closed reason": "Motivo del cierre",
	Company: "Empresa",
	"Company domain": "Dominio de la empresa",
	Contacts: "Contactos",
	Country: "País",
	Created: "Creado",
	Currency: "Moneda",
	Domain: "Dominio",
	Email: "Correo",
	"Expected close": "Cierre previsto",
	"First name": "Nombre",
	Industry: "Sector",
	"Last activity": "Última actividad",
	"Last name": "Apellido",
	LinkedIn: "LinkedIn",
	Name: "Nombre",
	"Open deals": "Negocios abiertos",
	Owner: "Responsable",
	"Owner email": "Correo del responsable",
	Persona: "Función",
	Phone: "Teléfono",
	Potential: "Potencial",
	"Reporting currency": "Moneda de referencia",
	Seniority: "Nivel",
	Source: "Origen",
	Stage: "Etapa",
	Status: "Estado",
	Title: "Puesto",
	Website: "Sitio web",
	"Demo booked": "Demo agendada",
	"Qualified to buy": "Calificado para comprar",
	"Decision maker in": "Decisor convencido",
	"Contract sent": "Contrato enviado",
	"Closed won": "Ganado",
	"Closed lost": "Perdido",
	Unqualified: "No califica",

	Customer: "Cliente",
	Interested: "Interesado",
	Watch: "En observación",
	High: "Alto",
	Medium: "Medio",
	Low: "Bajo",

	Manual: "Manual",
	Import: "Importación",
	Calendar: "Calendario",
	Tracking: "Tracking",

	companies: "empresas",
	contacts: "contactos",
	deals: "negocios",
} satisfies Record<ExportKey, string>;

const FRENCH = {
	Amount: "Montant",
	"Amount in reporting currency": "Montant en devise de reporting",
	Archived: "Archivé",
	City: "Ville",
	Closed: "Clôturé",
	"Closed reason": "Motif de la clôture",
	Company: "Entreprise",
	"Company domain": "Domaine de l'entreprise",
	Contacts: "Contacts",
	Country: "Pays",
	Created: "Créé",
	Currency: "Devise",
	Domain: "Domaine",
	Email: "E-mail",
	"Expected close": "Clôture prévue",
	"First name": "Prénom",
	Industry: "Secteur",
	"Last activity": "Dernière activité",
	"Last name": "Nom",
	LinkedIn: "LinkedIn",
	Name: "Nom",
	"Open deals": "Affaires ouvertes",
	Owner: "Responsable",
	"Owner email": "E-mail du responsable",
	Persona: "Fonction",
	Phone: "Téléphone",
	Potential: "Potentiel",
	"Reporting currency": "Devise de reporting",
	Seniority: "Niveau",
	Source: "Origine",
	Stage: "Étape",
	Status: "Statut",
	Title: "Poste",
	Website: "Site web",
	"Demo booked": "Démo planifiée",
	"Qualified to buy": "Qualifié à l'achat",
	"Decision maker in": "Décideur convaincu",
	"Contract sent": "Contrat envoyé",
	"Closed won": "Gagné",
	"Closed lost": "Perdu",
	Unqualified: "Non qualifié",

	Customer: "Client",
	Interested: "Intéressé",
	Watch: "À surveiller",
	High: "Élevé",
	Medium: "Moyen",
	Low: "Faible",

	Manual: "Manuel",
	Import: "Import",
	Calendar: "Calendrier",
	Tracking: "Tracking",

	companies: "entreprises",
	contacts: "contacts",
	deals: "affaires",
} satisfies Record<ExportKey, string>;

const PORTUGUESE = {
	Amount: "Valor",
	"Amount in reporting currency": "Valor na moeda de relatório",
	Archived: "Arquivado",
	City: "Cidade",
	Closed: "Fechado",
	"Closed reason": "Motivo do fechamento",
	Company: "Empresa",
	"Company domain": "Domínio da empresa",
	Contacts: "Contatos",
	Country: "País",
	Created: "Criado",
	Currency: "Moeda",
	Domain: "Domínio",
	Email: "E-mail",
	"Expected close": "Fechamento previsto",
	"First name": "Nome",
	Industry: "Setor",
	"Last activity": "Última atividade",
	"Last name": "Sobrenome",
	LinkedIn: "LinkedIn",
	Name: "Nome",
	"Open deals": "Negócios abertos",
	Owner: "Responsável",
	"Owner email": "E-mail do responsável",
	Persona: "Função",
	Phone: "Telefone",
	Potential: "Potencial",
	"Reporting currency": "Moeda de relatório",
	Seniority: "Nível",
	Source: "Origem",
	Stage: "Etapa",
	Status: "Status",
	Title: "Cargo",
	Website: "Site",
	"Demo booked": "Demonstração agendada",
	"Qualified to buy": "Qualificado para comprar",
	"Decision maker in": "Decisor convencido",
	"Contract sent": "Contrato enviado",
	"Closed won": "Ganho",
	"Closed lost": "Perdido",
	Unqualified: "Não qualificado",

	Customer: "Cliente",
	Interested: "Interessado",
	Watch: "Em observação",
	High: "Alto",
	Medium: "Médio",
	Low: "Baixo",

	Manual: "Manual",
	Import: "Importação",
	Calendar: "Calendário",
	Tracking: "Tracking",

	companies: "empresas",
	contacts: "contatos",
	deals: "negocios",
} satisfies Record<ExportKey, string>;

const TURKISH = {
	Amount: "Tutar",
	"Amount in reporting currency": "Raporlama para biriminde tutar",
	Archived: "Arşivlendi",
	City: "Şehir",
	Closed: "Kapandı",
	"Closed reason": "Kapanma nedeni",
	Company: "Şirket",
	"Company domain": "Şirket alan adı",
	Contacts: "Kişiler",
	Country: "Ülke",
	Created: "Oluşturuldu",
	Currency: "Para birimi",
	Domain: "Alan adı",
	Email: "E-posta",
	"Expected close": "Beklenen kapanış",
	"First name": "Ad",
	Industry: "Sektör",
	"Last activity": "Son etkinlik",
	"Last name": "Soyad",
	LinkedIn: "LinkedIn",
	Name: "Ad",
	"Open deals": "Açık fırsatlar",
	Owner: "Sorumlu",
	"Owner email": "Sorumlunun e-postası",
	Persona: "Rol",
	Phone: "Telefon",
	Potential: "Potansiyel",
	"Reporting currency": "Raporlama para birimi",
	Seniority: "Kıdem",
	Source: "Kaynak",
	Stage: "Aşama",
	Status: "Durum",
	Title: "Unvan",
	Website: "Web sitesi",
	"Demo booked": "Demo planlandı",
	"Qualified to buy": "Satın almaya uygun",
	"Decision maker in": "Karar verici ikna edildi",
	"Contract sent": "Sözleşme gönderildi",
	"Closed won": "Kazanıldı",
	"Closed lost": "Kaybedildi",
	Unqualified: "Uygun değil",

	Customer: "Müşteri",
	Interested: "İlgileniyor",
	Watch: "İzlemede",
	High: "Yüksek",
	Medium: "Orta",
	Low: "Düşük",

	Manual: "Elle",
	Import: "İçe aktarma",
	Calendar: "Takvim",
	Tracking: "Tracking",

	companies: "sirketler",
	contacts: "kisiler",
	deals: "firsatlar",
} satisfies Record<ExportKey, string>;

const CHINESE = {
	Amount: "金额",
	"Amount in reporting currency": "报告货币金额",
	Archived: "已归档",
	City: "城市",
	Closed: "已关闭",
	"Closed reason": "关闭原因",
	Company: "公司",
	"Company domain": "公司域名",
	Contacts: "联系人",
	Country: "国家",
	Created: "创建时间",
	Currency: "货币",
	Domain: "域名",
	Email: "邮箱",
	"Expected close": "预计成交",
	"First name": "名",
	Industry: "行业",
	"Last activity": "最近活动",
	"Last name": "姓",
	LinkedIn: "LinkedIn",
	Name: "名称",
	"Open deals": "进行中的交易",
	Owner: "负责人",
	"Owner email": "负责人邮箱",
	Persona: "角色",
	Phone: "电话",
	Potential: "潜力",
	"Reporting currency": "报告货币",
	Seniority: "职级",
	Source: "来源",
	Stage: "阶段",
	Status: "状态",
	Title: "职位",
	Website: "网站",
	"Demo booked": "已预约演示",
	"Qualified to buy": "已确认购买意向",
	"Decision maker in": "决策者已认可",
	"Contract sent": "合同已发送",
	"Closed won": "已赢单",
	"Closed lost": "已输单",
	Unqualified: "不合适",

	Customer: "客户",
	Interested: "有兴趣",
	Watch: "观察中",
	High: "高",
	Medium: "中",
	Low: "低",

	Manual: "手动",
	Import: "导入",
	Calendar: "日历",
	Tracking: "Tracking",

	companies: "companies",
	contacts: "contacts",
	deals: "deals",
} satisfies Record<ExportKey, string>;

export const EXPORT_WORDS = {
	de: GERMAN,
	es: SPANISH,
	fr: FRENCH,
	"pt-BR": PORTUGUESE,
	tr: TURKISH,
	"zh-Hans": CHINESE,
} satisfies Record<Translated, Record<ExportKey, string>>;

export function exportWord(locale: Locale, english: string): string {
	if (locale === "en") return english;

	const words: Record<string, string> = EXPORT_WORDS[locale];

	return words[english] ?? english;
}
