import type { Lines } from "./language";

export const COPY = {
	model: {
		noProvider: {
			en: "No model provider is set up. Add an OpenRouter, OpenAI or Anthropic key under Settings, AI, or sign in with ChatGPT there.",
			de: "Es ist kein Modellanbieter eingerichtet. Hinterlege unter Einstellungen, KI einen Schlüssel für OpenRouter, OpenAI oder Anthropic, oder melde dich dort mit ChatGPT an.",
			es: "No hay ningún proveedor de modelos configurado. Añade una clave de OpenRouter, OpenAI o Anthropic en Ajustes, IA, o inicia sesión allí con ChatGPT.",
			fr: "Aucun fournisseur de modèle n'est configuré. Ajoute une clé OpenRouter, OpenAI ou Anthropic dans Paramètres, IA, ou connecte-toi avec ChatGPT à cet endroit.",
			"pt-BR":
				"Nenhum provedor de modelo está configurado. Adicione uma chave da OpenRouter, OpenAI ou Anthropic em Configurações, IA, ou entre com o ChatGPT ali.",
			tr: "Hiçbir model sağlayıcı ayarlanmadı. Ayarlar, Yapay Zeka bölümüne bir OpenRouter, OpenAI veya Anthropic anahtarı ekle ya da orada ChatGPT ile giriş yap.",
			"zh-Hans":
				"尚未设置任何模型服务商。请在设置 › AI 中添加 OpenRouter、OpenAI 或 Anthropic 密钥，或在那里用 ChatGPT 登录。",
		},
		fixedUnavailable: {
			en: "The AI service is not available right now. The work continues when it is back.",
			de: "Der KI-Dienst ist gerade nicht erreichbar. Die Arbeit geht weiter, sobald er wieder da ist.",
			es: "El servicio de IA no está disponible ahora. El trabajo continúa cuando vuelva.",
			fr: "Le service d'IA n'est pas disponible pour le moment. Le travail reprend dès son retour.",
			"pt-BR":
				"O serviço de IA não está disponível agora. O trabalho continua quando ele voltar.",
			tr: "Yapay zeka hizmeti şu anda kullanılamıyor. Hizmet geri geldiğinde iş devam eder.",
			"zh-Hans": "AI 服务暂时不可用。服务恢复后工作会继续。",
		},
		fixedBusy: {
			en: "The AI service is busy right now. The work continues when it is free again.",
			de: "Der KI-Dienst ist gerade ausgelastet. Die Arbeit geht weiter, sobald er wieder frei ist.",
			es: "El servicio de IA está ocupado ahora. El trabajo continúa cuando vuelva a estar libre.",
			fr: "Le service d'IA est occupé pour le moment. Le travail reprend dès qu'il est de nouveau libre.",
			"pt-BR":
				"O serviço de IA está ocupado agora. O trabalho continua quando ele estiver livre de novo.",
			tr: "Yapay zeka hizmeti şu anda meşgul. Hizmet yeniden boşaldığında iş devam eder.",
			"zh-Hans": "AI 服务目前繁忙。空闲后工作会继续。",
		},
		allAtLimit: {
			en: "Every configured model provider is at its usage limit. The work waits for the next reset.",
			de: "Jeder eingerichtete Modellanbieter hat sein Nutzungslimit erreicht. Die Arbeit wartet auf das nächste Zurücksetzen.",
			es: "Todos los proveedores de modelos configurados han alcanzado su límite de uso. El trabajo espera al próximo reinicio.",
			fr: "Chaque fournisseur de modèle configuré a atteint sa limite d'utilisation. Le travail attend la prochaine remise à zéro.",
			"pt-BR":
				"Todos os provedores de modelo configurados atingiram o limite de uso. O trabalho espera a próxima renovação.",
			tr: "Ayarlanan her model sağlayıcı kullanım sınırına ulaştı. İş bir sonraki sıfırlamayı bekliyor.",
			"zh-Hans":
				"所有已配置的模型服务商都已达到使用上限。工作将等待下一次重置。",
		},
		chatgptSpent: (days: number | null): Lines => {
			const plural = days !== 1;
			return {
				en: `The ChatGPT subscription has used up its window, and no other provider is set up. The agent starts again when the limit resets${days === null ? "" : ` in ${days} ${plural ? "days" : "day"}`}. Add an OpenRouter, OpenAI or Anthropic key under Settings, AI to keep working now.`,
				de: `Das ChatGPT-Abo hat sein Zeitfenster aufgebraucht, und kein anderer Anbieter ist eingerichtet. Der Agent startet wieder, wenn das Limit zurückgesetzt wird${days === null ? "" : `, in ${days} ${plural ? "Tagen" : "Tag"}`}. Hinterlege unter Einstellungen, KI einen Schlüssel für OpenRouter, OpenAI oder Anthropic, um jetzt weiterzuarbeiten.`,
				es: `La suscripción de ChatGPT ha agotado su ventana y no hay otro proveedor configurado. El agente vuelve a empezar cuando se reinicie el límite${days === null ? "" : `, dentro de ${days} ${plural ? "días" : "día"}`}. Añade una clave de OpenRouter, OpenAI o Anthropic en Ajustes, IA para seguir trabajando ahora.`,
				fr: `L'abonnement ChatGPT a épuisé sa fenêtre et aucun autre fournisseur n'est configuré. L'agent reprend quand la limite est remise à zéro${days === null ? "" : `, dans ${days} ${plural ? "jours" : "jour"}`}. Ajoute une clé OpenRouter, OpenAI ou Anthropic dans Paramètres, IA pour continuer dès maintenant.`,
				"pt-BR": `A assinatura do ChatGPT esgotou sua janela e nenhum outro provedor está configurado. O agente recomeça quando o limite for renovado${days === null ? "" : `, em ${days} ${plural ? "dias" : "dia"}`}. Adicione uma chave da OpenRouter, OpenAI ou Anthropic em Configurações, IA para continuar agora.`,
				tr: `ChatGPT aboneliği zaman penceresini doldurdu ve başka bir sağlayıcı ayarlı değil. Sınır sıfırlandığında agent yeniden başlar${days === null ? "" : `, ${days} gün içinde`}. Şimdi çalışmaya devam etmek için Ayarlar, Yapay Zeka bölümüne bir OpenRouter, OpenAI veya Anthropic anahtarı ekle.`,
				"zh-Hans": `ChatGPT 订阅的额度窗口已用完，且没有设置其他服务商。${days === null ? "限额重置后" : `${days} 天后限额重置，届时`}智能体会重新开始。如需现在继续工作，请在设置 › AI 中添加 OpenRouter、OpenAI 或 Anthropic 密钥。`,
			};
		},
	},

	functions: {
		off: {
			en: "Switched off in Settings, Functions. Nothing was done.",
			de: "Unter Einstellungen, Funktionen ausgeschaltet. Es wurde nichts getan.",
			es: "Desactivado en Ajustes, Funciones. No se ha hecho nada.",
			fr: "Désactivé dans Paramètres, Fonctions. Rien n'a été fait.",
			"pt-BR": "Desligado em Configurações, Funções. Nada foi feito.",
			tr: "Ayarlar, Fonksiyonlar bölümünde kapatıldı. Hiçbir şey yapılmadı.",
			"zh-Hans": "已在设置 › 功能中关闭。未执行任何操作。",
		},
	},

	tasks: {
		noThreadId: {
			en: "No thread id on the task.",
			de: "Die Aufgabe nennt keinen Verlauf.",
			es: "La tarea no indica ninguna conversación.",
			fr: "La tâche ne désigne aucune conversation.",
			"pt-BR": "A tarefa não indica nenhuma conversa.",
			tr: "Görev bir yazışma belirtmiyor.",
			"zh-Hans": "该任务没有指明对话。",
		},
		recordGone: {
			en: "The record this names is gone.",
			de: "Der Datensatz, den sie nennt, ist weg.",
			es: "El registro que indica ya no existe.",
			fr: "La fiche qu'elle désigne n'existe plus.",
			"pt-BR": "O registro indicado não existe mais.",
			tr: "Belirttiği kayıt artık yok.",
			"zh-Hans": "它指向的记录已不存在。",
		},
		queued: (runs: number, webhooks: number): Lines => ({
			en: `${runs === 1 ? "Queued 1 matching agent run." : `Queued ${runs} matching agent runs.`} ${webhooks === 1 ? "Queued 1 webhook." : `Queued ${webhooks} webhooks.`}`,
			de: `${runs === 1 ? "1 passender Agentenlauf eingereiht." : `${runs} passende Agentenläufe eingereiht.`} ${webhooks === 1 ? "1 Webhook eingereiht." : `${webhooks} Webhooks eingereiht.`}`,
			es: `${runs === 1 ? "1 ejecución de agente en cola." : `${runs} ejecuciones de agente en cola.`} ${webhooks === 1 ? "1 webhook en cola." : `${webhooks} webhooks en cola.`}`,
			fr: `${runs === 1 ? "1 exécution d'agent en file d'attente." : `${runs} exécutions d'agent en file d'attente.`} ${webhooks === 1 ? "1 webhook en file d'attente." : `${webhooks} webhooks en file d'attente.`}`,
			"pt-BR": `${runs === 1 ? "1 execução de agente na fila." : `${runs} execuções de agente na fila.`} ${webhooks === 1 ? "1 webhook na fila." : `${webhooks} webhooks na fila.`}`,
			tr: `${runs} eşleşen agent çalıştırması sıraya alındı. ${webhooks} webhook sıraya alındı.`,
			"zh-Hans": `已排队 ${runs} 个匹配的智能体运行。已排队 ${webhooks} 个 webhook。`,
		}),
		droppedArchived: {
			en: "Dropped: the record was archived before the work started.",
			de: "Verworfen: Der Datensatz wurde archiviert, bevor die Arbeit begann.",
			es: "Descartada: el registro se archivó antes de empezar el trabajo.",
			fr: "Abandonnée : la fiche a été archivée avant le début du travail.",
			"pt-BR":
				"Descartada: o registro foi arquivado antes de o trabalho começar.",
			tr: "Bırakıldı: kayıt, iş başlamadan önce arşivlendi.",
			"zh-Hans": "已放弃：工作开始前该记录已被归档。",
		},
		droppedSample: {
			en: "Dropped: this record is sample data, so nothing was researched and nothing was spent.",
			de: "Verworfen: Dieser Datensatz sind Beispieldaten, also wurde nichts recherchiert und nichts ausgegeben.",
			es: "Descartada: este registro son datos de ejemplo, así que no se ha investigado nada ni se ha gastado nada.",
			fr: "Abandonnée : cette fiche est une donnée d'exemple, donc rien n'a été recherché et rien n'a été dépensé.",
			"pt-BR":
				"Descartada: este registro é um dado de exemplo, então nada foi pesquisado e nada foi gasto.",
			tr: "Bırakıldı: bu kayıt örnek veri, bu yüzden hiçbir şey araştırılmadı ve hiçbir harcama yapılmadı.",
			"zh-Hans":
				"已放弃：这条记录是示例数据，因此没有进行任何研究，也没有产生任何花费。",
		},
		landed: {
			en: "The record was already up to date when this was checked again.",
			de: "Der Datensatz war bei der erneuten Prüfung schon aktuell.",
			es: "El registro ya estaba al día cuando se volvió a comprobar.",
			fr: "La fiche était déjà à jour lors de la nouvelle vérification.",
			"pt-BR": "O registro já estava atualizado quando foi verificado de novo.",
			tr: "Yeniden kontrol edildiğinde kayıt zaten günceldi.",
			"zh-Hans": "再次检查时，该记录已经是最新的。",
		},
		retiredError: {
			en: "Research was attempted several times and never completed.",
			de: "Die Recherche wurde mehrmals versucht und nie abgeschlossen.",
			es: "La investigación se intentó varias veces y nunca terminó.",
			fr: "La recherche a été tentée plusieurs fois et n'a jamais abouti.",
			"pt-BR": "A pesquisa foi tentada várias vezes e nunca terminou.",
			tr: "Araştırma birkaç kez denendi ve hiç tamamlanmadı.",
			"zh-Hans": "已多次尝试研究，但始终没有完成。",
		},
		untargeted: {
			en: "No record was ever attached to this task, so it can never be worked. Retired.",
			de: "Dieser Aufgabe war nie ein Datensatz zugeordnet, also kann sie nie bearbeitet werden. Beendet.",
			es: "Esta tarea nunca tuvo un registro asociado, así que nunca se podrá trabajar. Retirada.",
			fr: "Aucune fiche n'a jamais été rattachée à cette tâche, elle ne peut donc jamais être traitée. Retirée.",
			"pt-BR":
				"Nenhum registro foi vinculado a esta tarefa, então ela nunca poderá ser feita. Encerrada.",
			tr: "Bu göreve hiç kayıt bağlanmadı, bu yüzden hiçbir zaman işlenemez. Kapatıldı.",
			"zh-Hans": "此任务从未关联任何记录，因此永远无法处理。已停用。",
		},
	},

	business: {
		alreadySet: {
			en: "The business rules are already set. I changed nothing.",
			de: "Die Geschäftsregeln stehen schon. Ich habe nichts geändert.",
			es: "Las reglas del negocio ya están definidas. No he cambiado nada.",
			fr: "Les règles de l'entreprise sont déjà définies. Je n'ai rien changé.",
			"pt-BR": "As regras do negócio já estão definidas. Não mudei nada.",
			tr: "İş kuralları zaten belirlendi. Hiçbir şeyi değiştirmedim.",
			"zh-Hans": "业务规则已经设定好了。我没有做任何更改。",
		},
		waiting: (needed: number, threads: number): Lines => ({
			en: `I am still waiting. I need ${needed} conversations or a readable website to say what this business sells. There are ${threads} conversations now.`,
			de: `Ich warte noch. Erst ab ${needed} Verläufen oder mit einer lesbaren Website kann ich sagen, womit hier gehandelt wird. Aktuell sind es ${threads}.`,
			es: `Sigo esperando. Necesito ${needed} conversaciones o un sitio web legible para saber qué vende este negocio. Ahora hay ${threads} conversaciones.`,
			fr: `J'attends encore. Il me faut ${needed} conversations ou un site web lisible pour dire ce que vend cette entreprise. Il y a ${threads} conversations pour l'instant.`,
			"pt-BR": `Ainda estou esperando. Preciso de ${needed} conversas ou de um site legível para dizer o que este negócio vende. Agora são ${threads} conversas.`,
			tr: `Hâlâ bekliyorum. Bu işletmenin ne sattığını söylemek için ${needed} yazışmaya veya okunabilir bir web sitesine ihtiyacım var. Şu anda ${threads} yazışma var.`,
			"zh-Hans": `我还在等待。需要 ${needed} 个对话或一个可读取的网站，才能判断这家企业卖什么。目前有 ${threads} 个对话。`,
		}),
		failed: (error: string): Lines => ({
			en: `I could not work out the business rules myself: ${error}`,
			de: `Ich konnte die Geschäftsregeln nicht selbst finden: ${error}`,
			es: `No he podido deducir yo mismo las reglas del negocio: ${error}`,
			fr: `Je n'ai pas pu déterminer moi-même les règles de l'entreprise : ${error}`,
			"pt-BR": `Não consegui descobrir sozinho as regras do negócio: ${error}`,
			tr: `İş kurallarını kendim çıkaramadım: ${error}`,
			"zh-Hans": `我无法自行确定业务规则：${error}`,
		}),
	},

	fields: {
		full: (limit: number): Lines => ({
			en: `Every record type already holds ${limit} fields or has that many waiting. I propose nothing until one is archived or dismissed.`,
			de: `Jeder Datensatztyp hat bereits ${limit} Felder oder so viele offene Vorschläge. Ich schlage nichts vor, bis eines archiviert oder abgelehnt ist.`,
			es: `Cada tipo de registro ya tiene ${limit} campos o tantas propuestas pendientes. No propongo nada hasta que se archive o se descarte uno.`,
			fr: `Chaque type de fiche contient déjà ${limit} champs ou autant de propositions en attente. Je ne propose rien tant qu'aucun n'est archivé ou refusé.`,
			"pt-BR": `Cada tipo de registro já tem ${limit} campos ou essa quantidade de propostas pendentes. Não proponho nada até que um seja arquivado ou descartado.`,
			tr: `Her kayıt türünde zaten ${limit} alan ya da o kadar bekleyen öneri var. Biri arşivlenene veya reddedilene kadar bir şey önermiyorum.`,
			"zh-Hans": `每种记录类型都已有 ${limit} 个字段或同样数量的待处理建议。在有字段被归档或拒绝之前，我不会再提出建议。`,
		}),
		noMail: {
			en: "There is no mail to read yet, so I propose no fields.",
			de: "Es gibt noch keine Mails zu lesen, deshalb schlage ich keine Felder vor.",
			es: "Todavía no hay correos que leer, así que no propongo campos.",
			fr: "Il n'y a encore aucun e-mail à lire, je ne propose donc aucun champ.",
			"pt-BR": "Ainda não há e-mails para ler, então não proponho campos.",
			tr: "Henüz okunacak e-posta yok, bu yüzden alan önermiyorum.",
			"zh-Hans": "目前还没有可读取的邮件，所以我不提出字段建议。",
		},
		nothingRepeats: (note: string): Lines => ({
			en: `Nothing in the mail repeats often enough to earn a field. ${note}`,
			de: `Nichts in den Mails wiederholt sich oft genug für ein eigenes Feld. ${note}`,
			es: `Nada en los correos se repite lo bastante como para merecer un campo. ${note}`,
			fr: `Rien dans les e-mails ne revient assez souvent pour mériter un champ. ${note}`,
			"pt-BR": `Nada nos e-mails se repete o suficiente para merecer um campo. ${note}`,
			tr: `E-postalarda hiçbir şey bir alanı hak edecek kadar sık tekrarlanmıyor. ${note}`,
			"zh-Hans": `邮件中没有任何内容重复到值得单独设一个字段。${note}`,
		}),
		proposed: (count: number, labels: string): Lines => ({
			en: `I propose ${count} field(s): ${labels}. Accept or dismiss each one on the Fields sheet.`,
			de: `Ich schlage ${count} Feld(er) vor: ${labels}. Nimm jedes unter Felder an oder lehne es ab.`,
			es: `Propongo ${count} campo(s): ${labels}. Acepta o descarta cada uno en Campos.`,
			fr: `Je propose ${count} champ(s) : ${labels}. Accepte ou refuse chacun dans Champs.`,
			"pt-BR": `Proponho ${count} campo(s): ${labels}. Aceite ou descarte cada um em Campos.`,
			tr: `${count} alan öneriyorum: ${labels}. Her birini Alanlar bölümünde kabul et veya reddet.`,
			"zh-Hans": `我建议 ${count} 个字段：${labels}。请在字段中逐个接受或拒绝。`,
		}),
		unreadable: (error: string): Lines => ({
			en: `I could not read a field proposal out of the mail: ${error}`,
			de: `Ich konnte aus den Mails keinen Feldvorschlag lesen: ${error}`,
			es: `No he podido sacar una propuesta de campo de los correos: ${error}`,
			fr: `Je n'ai pas pu tirer une proposition de champ des e-mails : ${error}`,
			"pt-BR": `Não consegui tirar uma proposta de campo dos e-mails: ${error}`,
			tr: `E-postalardan bir alan önerisi çıkaramadım: ${error}`,
			"zh-Hans": `我无法从邮件中读出字段建议：${error}`,
		}),
	},

	rules: {
		good: {
			en: "Worth it",
			de: "Lohnt sich",
			es: "Interesante",
			fr: "Intéressant",
			"pt-BR": "Vale a pena",
			tr: "Değer",
			"zh-Hans": "值得",
		},
		bad: {
			en: "Not for us",
			de: "Nichts für uns",
			es: "No es para nosotros",
			fr: "Pas pour nous",
			"pt-BR": "Não é para nós",
			tr: "Bize göre değil",
			"zh-Hans": "不适合我们",
		},
		seenOne: (label: string): Lines => ({
			en: `I see 1 verdict, and it says "${label}".`,
			de: `Ich sehe 1 Urteil, und es sagt "${label}".`,
			es: `Veo 1 valoración, y dice "${label}".`,
			fr: `Je vois 1 avis, et il dit "${label}".`,
			"pt-BR": `Vejo 1 avaliação, e ela diz "${label}".`,
			tr: `1 değerlendirme görüyorum ve "${label}" diyor.`,
			"zh-Hans": `我看到 1 条评价，它是"${label}"。`,
		}),
		seenMany: (count: number, label: string): Lines => ({
			en: `I see ${count} verdicts, and all of them say "${label}".`,
			de: `Ich sehe ${count} Urteile, und alle sagen "${label}".`,
			es: `Veo ${count} valoraciones, y todas dicen "${label}".`,
			fr: `Je vois ${count} avis, et tous disent "${label}".`,
			"pt-BR": `Vejo ${count} avaliações, e todas dizem "${label}".`,
			tr: `${count} değerlendirme görüyorum ve hepsi "${label}" diyor.`,
			"zh-Hans": `我看到 ${count} 条评价，全部是"${label}"。`,
		}),
		atLeastOne: {
			en: "at least one person",
			de: "mindestens eine Person",
			es: "al menos una persona",
			fr: "au moins une personne",
			"pt-BR": "pelo menos uma pessoa",
			tr: "en az bir kişi",
			"zh-Hans": "至少一个人",
		},
		atLeast: (count: number): Lines => ({
			en: `at least ${count} people`,
			de: `mindestens ${count} Personen`,
			es: `al menos ${count} personas`,
			fr: `au moins ${count} personnes`,
			"pt-BR": `pelo menos ${count} pessoas`,
			tr: `en az ${count} kişi`,
			"zh-Hans": `至少 ${count} 个人`,
		}),
		noVerdict: (good: string, bad: string): Lines => ({
			en: `I did not change the rules. There is no verdict yet. In Win-back, first mark people as "${good}" or "${bad}".`,
			de: `Ich habe die Regeln nicht angepasst. Es gibt noch kein Urteil. Markiere in Zurückgewinnen zuerst Personen mit "${good}" oder "${bad}".`,
			es: `No he cambiado las reglas. Todavía no hay ninguna valoración. En Recuperar, marca primero personas como "${good}" o "${bad}".`,
			fr: `Je n'ai pas modifié les règles. Il n'y a encore aucun avis. Dans Reconquête, marque d'abord des personnes comme "${good}" ou "${bad}".`,
			"pt-BR": `Não mudei as regras. Ainda não há nenhuma avaliação. Em Reconquistar, marque primeiro pessoas como "${good}" ou "${bad}".`,
			tr: `Kuralları değiştirmedim. Henüz hiç değerlendirme yok. Geri kazan bölümünde önce kişileri "${good}" veya "${bad}" olarak işaretle.`,
			"zh-Hans": `我没有修改规则。目前还没有任何评价。请先在赢回中把人标记为"${good}"或"${bad}"。`,
		}),
		needGood: (seen: string, needed: string, good: string): Lines => ({
			en: `I did not change the rules. ${seen} I need ${needed} marked "${good}". Then I learn what a good contact looks like.`,
			de: `Ich habe die Regeln nicht angepasst. ${seen} Ich brauche ${needed} mit "${good}". Dann lerne ich, wie ein guter Kontakt aussieht.`,
			es: `No he cambiado las reglas. ${seen} Necesito ${needed} marcadas como "${good}". Así aprendo cómo es un buen contacto.`,
			fr: `Je n'ai pas modifié les règles. ${seen} Il me faut ${needed} marquées "${good}". J'apprends alors à quoi ressemble un bon contact.`,
			"pt-BR": `Não mudei as regras. ${seen} Preciso de ${needed} marcadas como "${good}". Assim aprendo como é um bom contato.`,
			tr: `Kuralları değiştirmedim. ${seen} "${good}" olarak işaretlenmiş ${needed} gerekiyor. Böylece iyi bir kişinin nasıl göründüğünü öğrenirim.`,
			"zh-Hans": `我没有修改规则。${seen}我需要${needed}被标记为"${good}"。这样我才能学会好的联系人是什么样子。`,
		}),
		needBad: (seen: string, needed: string, bad: string): Lines => ({
			en: `I did not change the rules. ${seen} I need ${needed} marked "${bad}". Then I learn whom to leave out.`,
			de: `Ich habe die Regeln nicht angepasst. ${seen} Ich brauche ${needed} mit "${bad}". Dann lerne ich, wen ich aussortieren soll.`,
			es: `No he cambiado las reglas. ${seen} Necesito ${needed} marcadas como "${bad}". Así aprendo a quién dejar fuera.`,
			fr: `Je n'ai pas modifié les règles. ${seen} Il me faut ${needed} marquées "${bad}". J'apprends alors qui laisser de côté.`,
			"pt-BR": `Não mudei as regras. ${seen} Preciso de ${needed} marcadas como "${bad}". Assim aprendo quem deixar de fora.`,
			tr: `Kuralları değiştirmedim. ${seen} "${bad}" olarak işaretlenmiş ${needed} gerekiyor. Böylece kimi dışarıda bırakacağımı öğrenirim.`,
			"zh-Hans": `我没有修改规则。${seen}我需要${needed}被标记为"${bad}"。这样我才能学会该排除谁。`,
		}),
		tuned: (count: number, note: string): Lines => ({
			en: `Rules tuned from ${count} verdicts: ${note}`,
			de: `Regeln aus ${count} Urteilen angepasst: ${note}`,
			es: `Reglas ajustadas a partir de ${count} valoraciones: ${note}`,
			fr: `Règles ajustées à partir de ${count} avis : ${note}`,
			"pt-BR": `Regras ajustadas a partir de ${count} avaliações: ${note}`,
			tr: `Kurallar ${count} değerlendirmeye göre ayarlandı: ${note}`,
			"zh-Hans": `已根据 ${count} 条评价调整规则：${note}`,
		}),
	},

	threads: {
		gone: {
			en: "The thread is gone.",
			de: "Der Verlauf ist weg.",
			es: "La conversación ya no existe.",
			fr: "La conversation n'existe plus.",
			"pt-BR": "A conversa não existe mais.",
			tr: "Yazışma artık yok.",
			"zh-Hans": "该对话已不存在。",
		},
		empty: {
			en: "The thread has no messages.",
			de: "Der Verlauf enthält keine Nachrichten.",
			es: "La conversación no tiene mensajes.",
			fr: "La conversation ne contient aucun message.",
			"pt-BR": "A conversa não tem mensagens.",
			tr: "Yazışmada hiç mesaj yok.",
			"zh-Hans": "该对话没有任何消息。",
		},
		offTopic: {
			en: "Not about the business.",
			de: "Nicht geschäftlich.",
			es: "No trata del negocio.",
			fr: "Ne concerne pas l'activité.",
			"pt-BR": "Não é sobre o negócio.",
			tr: "İşle ilgili değil.",
			"zh-Hans": "与业务无关。",
		},
		offTopicBecause: (why: string): Lines => ({
			en: `Not about the business: ${why}`,
			de: `Nicht geschäftlich: ${why}`,
			es: `No trata del negocio: ${why}`,
			fr: `Ne concerne pas l'activité : ${why}`,
			"pt-BR": `Não é sobre o negócio: ${why}`,
			tr: `İşle ilgili değil: ${why}`,
			"zh-Hans": `与业务无关：${why}`,
		}),
		units: (count: number): Lines => ({
			en: `${count} units`,
			de: `${count} Einheiten`,
			es: `${count} unidades`,
			fr: `${count} unités`,
			"pt-BR": `${count} unidades`,
			tr: `${count} birim`,
			"zh-Hans": `${count} 个单位`,
		}),
		allLined: {
			en: "Every message already has a line.",
			de: "Jede Nachricht hat schon eine Zeile.",
			es: "Cada mensaje ya tiene una línea.",
			fr: "Chaque message a déjà sa ligne.",
			"pt-BR": "Cada mensagem já tem uma linha.",
			tr: "Her mesajın zaten bir satırı var.",
			"zh-Hans": "每条消息都已经有一行摘要。",
		},
		lined: (count: number): Lines => ({
			en:
				count === 1
					? "1 message now has a line."
					: `${count} messages now have a line.`,
			de:
				count === 1
					? "1 Nachricht hat jetzt eine Zeile."
					: `${count} Nachrichten haben jetzt eine Zeile.`,
			es:
				count === 1
					? "1 mensaje tiene ahora una línea."
					: `${count} mensajes tienen ahora una línea.`,
			fr:
				count === 1
					? "1 message a désormais sa ligne."
					: `${count} messages ont désormais leur ligne.`,
			"pt-BR":
				count === 1
					? "1 mensagem agora tem uma linha."
					: `${count} mensagens agora têm uma linha.`,
			tr: `${count} mesajın artık bir satırı var.`,
			"zh-Hans": `现在有 ${count} 条消息有了一行摘要。`,
		}),
	},

	playbook: {
		tooFew: (count: number): Lines => ({
			en: `Only ${count} sent emails so far. Nothing to learn yet.`,
			de: `Bisher nur ${count} gesendete Mails. Noch nichts zu lernen.`,
			es: `Solo ${count} correos enviados hasta ahora. Todavía no hay nada que aprender.`,
			fr: `Seulement ${count} e-mails envoyés pour l'instant. Rien à apprendre encore.`,
			"pt-BR": `Só ${count} e-mails enviados até agora. Ainda não há nada para aprender.`,
			tr: `Şimdiye kadar yalnızca ${count} e-posta gönderildi. Henüz öğrenilecek bir şey yok.`,
			"zh-Hans": `目前只发送了 ${count} 封邮件，还没有可学习的内容。`,
		}),
		learned: (count: number, summary: string): Lines => ({
			en: `Learned from ${count} sent emails: ${summary}`,
			de: `Aus ${count} gesendeten Mails gelernt: ${summary}`,
			es: `Aprendido de ${count} correos enviados: ${summary}`,
			fr: `Appris de ${count} e-mails envoyés : ${summary}`,
			"pt-BR": `Aprendido com ${count} e-mails enviados: ${summary}`,
			tr: `${count} gönderilmiş e-postadan öğrenildi: ${summary}`,
			"zh-Hans": `已从 ${count} 封已发送邮件中学习：${summary}`,
		}),
	},

	deals: {
		skipped: {
			en: "A follow up on this deal is not worth sending now. No note was written.",
			de: "Eine Nachfrage zu diesem Deal lohnt sich gerade nicht. Es wurde keine Notiz geschrieben.",
			es: "Ahora no vale la pena hacer un seguimiento de este trato. No se ha escrito ninguna nota.",
			fr: "Une relance sur cette affaire ne vaut pas la peine pour l'instant. Aucune note n'a été écrite.",
			"pt-BR":
				"Um acompanhamento deste negócio não vale a pena agora. Nenhuma nota foi escrita.",
			tr: "Bu fırsat için şu anda takip mesajı göndermeye değmez. Not yazılmadı.",
			"zh-Hans": "现在不值得跟进这笔交易。没有写备注。",
		},
		closed: {
			en: "The deal is closed or gone. No note was written.",
			de: "Der Deal ist abgeschlossen oder weg. Es wurde keine Notiz geschrieben.",
			es: "El trato está cerrado o ya no existe. No se ha escrito ninguna nota.",
			fr: "L'affaire est close ou n'existe plus. Aucune note n'a été écrite.",
			"pt-BR":
				"O negócio está fechado ou não existe mais. Nenhuma nota foi escrita.",
			tr: "Fırsat kapandı veya artık yok. Not yazılmadı.",
			"zh-Hans": "该交易已关闭或已不存在。没有写备注。",
		},
		moved: {
			en: "The deal moved after it was queued. No note was written.",
			de: "Der Deal hat sich bewegt, nachdem er eingereiht wurde. Es wurde keine Notiz geschrieben.",
			es: "El trato se movió después de ponerse en cola. No se ha escrito ninguna nota.",
			fr: "L'affaire a bougé après sa mise en file d'attente. Aucune note n'a été écrite.",
			"pt-BR":
				"O negócio mudou depois de entrar na fila. Nenhuma nota foi escrita.",
			tr: "Fırsat sıraya alındıktan sonra hareket etti. Not yazılmadı.",
			"zh-Hans": "该交易在排队后有了新进展。没有写备注。",
		},
		gone: {
			en: "The deal is gone. No note was written.",
			de: "Der Deal ist weg. Es wurde keine Notiz geschrieben.",
			es: "El trato ya no existe. No se ha escrito ninguna nota.",
			fr: "L'affaire n'existe plus. Aucune note n'a été écrite.",
			"pt-BR": "O negócio não existe mais. Nenhuma nota foi escrita.",
			tr: "Fırsat artık yok. Not yazılmadı.",
			"zh-Hans": "该交易已不存在。没有写备注。",
		},
		nothingToRead: {
			en: "There is no mail and no note to read. No note was written.",
			de: "Es gibt keine Mail und keine Notiz zu lesen. Es wurde keine Notiz geschrieben.",
			es: "No hay ningún correo ni ninguna nota que leer. No se ha escrito ninguna nota.",
			fr: "Il n'y a aucun e-mail ni aucune note à lire. Aucune note n'a été écrite.",
			"pt-BR": "Não há e-mail nem nota para ler. Nenhuma nota foi escrita.",
			tr: "Okunacak e-posta veya not yok. Not yazılmadı.",
			"zh-Hans": "没有可读的邮件或备注。没有写备注。",
		},
		wrote: (subject: string): Lines => ({
			en: `Wrote the next step: ${subject}`,
			de: `Nächsten Schritt geschrieben: ${subject}`,
			es: `Siguiente paso escrito: ${subject}`,
			fr: `Prochaine étape écrite : ${subject}`,
			"pt-BR": `Próximo passo escrito: ${subject}`,
			tr: `Sonraki adım yazıldı: ${subject}`,
			"zh-Hans": `已写下下一步：${subject}`,
		}),
	},

	drafts: {
		contactGone: {
			en: "The contact is gone.",
			de: "Der Kontakt ist weg.",
			es: "El contacto ya no existe.",
			fr: "Le contact n'existe plus.",
			"pt-BR": "O contato não existe mais.",
			tr: "Kişi artık yok.",
			"zh-Hans": "该联系人已不存在。",
		},
		noConversation: {
			en: "There is no conversation to build a draft on.",
			de: "Es gibt keinen Verlauf, auf dem ein Entwurf aufbauen kann.",
			es: "No hay ninguna conversación sobre la que redactar un borrador.",
			fr: "Il n'y a aucune conversation sur laquelle bâtir un brouillon.",
			"pt-BR": "Não há conversa para basear um rascunho.",
			tr: "Taslak oluşturmak için bir yazışma yok.",
			"zh-Hans": "没有可以据此写草稿的对话。",
		},
		ready: (subject: string): Lines => ({
			en: `A draft is ready: ${subject}`,
			de: `Ein Entwurf ist fertig: ${subject}`,
			es: `Hay un borrador listo: ${subject}`,
			fr: `Un brouillon est prêt : ${subject}`,
			"pt-BR": `Um rascunho está pronto: ${subject}`,
			tr: `Bir taslak hazır: ${subject}`,
			"zh-Hans": `草稿已就绪：${subject}`,
		}),
		rewritten: (subject: string): Lines => ({
			en: `The draft is rewritten: ${subject}`,
			de: `Der Entwurf ist neu geschrieben: ${subject}`,
			es: `El borrador se ha reescrito: ${subject}`,
			fr: `Le brouillon est réécrit : ${subject}`,
			"pt-BR": `O rascunho foi reescrito: ${subject}`,
			tr: `Taslak yeniden yazıldı: ${subject}`,
			"zh-Hans": `草稿已重写：${subject}`,
		}),
	},

	clean: {
		skipped: {
			en: "Their mail carries no signature block. Nothing changed.",
			de: "Ihre Mails tragen keinen Signaturblock. Nichts wurde geändert.",
			es: "Sus correos no llevan bloque de firma. No ha cambiado nada.",
			fr: "Leurs e-mails ne portent aucun bloc de signature. Rien n'a changé.",
			"pt-BR":
				"Os e-mails dessa pessoa não trazem bloco de assinatura. Nada mudou.",
			tr: "E-postalarında imza bloğu yok. Hiçbir şey değişmedi.",
			"zh-Hans": "对方的邮件没有签名档。没有任何更改。",
		},
		noContact: {
			en: "No contact or no email address.",
			de: "Kein Kontakt oder keine E-Mail-Adresse.",
			es: "No hay contacto o no hay dirección de correo.",
			fr: "Pas de contact ou pas d'adresse e-mail.",
			"pt-BR": "Não há contato ou não há endereço de e-mail.",
			tr: "Kişi veya e-posta adresi yok.",
			"zh-Hans": "没有联系人或没有邮箱地址。",
		},
		noMail: {
			en: "No email from them to read.",
			de: "Keine Mail von ihnen zu lesen.",
			es: "No hay ningún correo suyo que leer.",
			fr: "Aucun e-mail de leur part à lire.",
			"pt-BR": "Não há e-mail dessa pessoa para ler.",
			tr: "Okunacak bir e-postaları yok.",
			"zh-Hans": "没有对方发来的邮件可读。",
		},
		ours: {
			en: "The only signature found was our own. Nothing changed.",
			de: "Die einzige gefundene Signatur war unsere eigene. Nichts wurde geändert.",
			es: "La única firma encontrada era la nuestra. No ha cambiado nada.",
			fr: "La seule signature trouvée était la nôtre. Rien n'a changé.",
			"pt-BR": "A única assinatura encontrada era a nossa. Nada mudou.",
			tr: "Bulunan tek imza bizimkiydi. Hiçbir şey değişmedi.",
			"zh-Hans": "找到的唯一签名是我们自己的。没有任何更改。",
		},
		confirmed: {
			en: "Signature confirmed what the record already had.",
			de: "Die Signatur hat bestätigt, was schon im Datensatz stand.",
			es: "La firma confirmó lo que ya tenía el registro.",
			fr: "La signature a confirmé ce que la fiche contenait déjà.",
			"pt-BR": "A assinatura confirmou o que o registro já tinha.",
			tr: "İmza, kayıtta zaten olanı doğruladı.",
			"zh-Hans": "签名确认了记录中已有的信息。",
		},
		cleaned: (changes: string): Lines => ({
			en: `Cleaned: ${changes}.`,
			de: `Bereinigt: ${changes}.`,
			es: `Limpiado: ${changes}.`,
			fr: `Nettoyé : ${changes}.`,
			"pt-BR": `Limpo: ${changes}.`,
			tr: `Temizlendi: ${changes}.`,
			"zh-Hans": `已清理：${changes}。`,
		}),
		proposed: {
			en: "proposed",
			de: "vorgeschlagen",
			es: "propuesto",
			fr: "proposé",
			"pt-BR": "proposto",
			tr: "önerildi",
			"zh-Hans": "已建议",
		},
		field: {
			name: {
				en: "name",
				de: "Name",
				es: "nombre",
				fr: "nom",
				"pt-BR": "nome",
				tr: "ad",
				"zh-Hans": "姓名",
			},
			title: {
				en: "title",
				de: "Position",
				es: "cargo",
				fr: "fonction",
				"pt-BR": "cargo",
				tr: "unvan",
				"zh-Hans": "职位",
			},
			phone: {
				en: "phone",
				de: "Telefon",
				es: "teléfono",
				fr: "téléphone",
				"pt-BR": "telefone",
				tr: "telefon",
				"zh-Hans": "电话",
			},
			company: {
				en: "company",
				de: "Firma",
				es: "empresa",
				fr: "entreprise",
				"pt-BR": "empresa",
				tr: "şirket",
				"zh-Hans": "公司",
			},
		},
	},

	brand: {
		noCompany: {
			en: "No such company.",
			de: "Diese Firma gibt es nicht.",
			es: "Esa empresa no existe.",
			fr: "Cette entreprise n'existe pas.",
			"pt-BR": "Essa empresa não existe.",
			tr: "Böyle bir şirket yok.",
			"zh-Hans": "没有这家公司。",
		},
		noDomainToLookUp: {
			en: "No domain to look up.",
			de: "Keine Domain zum Nachschlagen.",
			es: "No hay ningún dominio que consultar.",
			fr: "Aucun domaine à consulter.",
			"pt-BR": "Não há domínio para consultar.",
			tr: "Bakılacak bir alan adı yok.",
			"zh-Hans": "没有可查询的域名。",
		},
		noDomain: {
			en: "No domain on this company.",
			de: "Diese Firma hat keine Domain.",
			es: "Esta empresa no tiene dominio.",
			fr: "Cette entreprise n'a pas de domaine.",
			"pt-BR": "Esta empresa não tem domínio.",
			tr: "Bu şirketin alan adı yok.",
			"zh-Hans": "这家公司没有域名。",
		},
		nothingToFill: {
			en: "Nothing to fill.",
			de: "Nichts zu füllen.",
			es: "No hay nada que rellenar.",
			fr: "Rien à remplir.",
			"pt-BR": "Nada para preencher.",
			tr: "Doldurulacak bir şey yok.",
			"zh-Hans": "没有需要填写的内容。",
		},
		alreadyThere: {
			en: "Everything found was already on the record.",
			de: "Alles Gefundene stand schon im Datensatz.",
			es: "Todo lo encontrado ya estaba en el registro.",
			fr: "Tout ce qui a été trouvé figurait déjà sur la fiche.",
			"pt-BR": "Tudo o que foi encontrado já estava no registro.",
			tr: "Bulunan her şey zaten kayıttaydı.",
			"zh-Hans": "找到的内容都已在记录中。",
		},
		filled: (fields: string, copied: number): Lines => ({
			en: `Filled ${fields}.${copied > 0 ? ` Copied ${copied} image(s) in-house.` : ""}`,
			de: `Gefüllt: ${fields}.${copied > 0 ? ` ${copied} Bild(er) in den eigenen Speicher kopiert.` : ""}`,
			es: `Rellenado: ${fields}.${copied > 0 ? ` ${copied} imagen(es) copiada(s) al almacenamiento propio.` : ""}`,
			fr: `Rempli : ${fields}.${copied > 0 ? ` ${copied} image(s) copiée(s) dans notre stockage.` : ""}`,
			"pt-BR": `Preenchido: ${fields}.${copied > 0 ? ` ${copied} imagem(ns) copiada(s) para o armazenamento próprio.` : ""}`,
			tr: `Dolduruldu: ${fields}.${copied > 0 ? ` ${copied} görsel kendi depomuza kopyalandı.` : ""}`,
			"zh-Hans": `已填写：${fields}。${copied > 0 ? `已将 ${copied} 张图片复制到自有存储。` : ""}`,
		}),
		siteSilent: (domain: string): Lines => ({
			en: `The website ${domain} did not answer with a page to read.`,
			de: `Die Website ${domain} hat keine lesbare Seite geliefert.`,
			es: `El sitio web ${domain} no respondió con una página legible.`,
			fr: `Le site ${domain} n'a renvoyé aucune page lisible.`,
			"pt-BR": `O site ${domain} não respondeu com uma página legível.`,
			tr: `${domain} web sitesi okunabilir bir sayfa döndürmedi.`,
			"zh-Hans": `网站 ${domain} 没有返回可读取的页面。`,
		}),
	},

	portraits: {
		noPhoto: {
			en: "No photo on the profile.",
			de: "Das Profil hat kein Foto.",
			es: "El perfil no tiene foto.",
			fr: "Le profil n'a pas de photo.",
			"pt-BR": "O perfil não tem foto.",
			tr: "Profilde fotoğraf yok.",
			"zh-Hans": "该资料没有照片。",
		},
		notTheirs: {
			en: "The profile was not established to be this person, so its photo is not theirs to use.",
			de: "Es ist nicht belegt, dass das Profil zu dieser Person gehört, also ist das Foto nicht ihres.",
			es: "No se ha comprobado que el perfil sea de esta persona, así que su foto no es suya para usarla.",
			fr: "Il n'est pas établi que ce profil soit celui de cette personne, sa photo n'est donc pas la sienne.",
			"pt-BR":
				"Não foi comprovado que o perfil é desta pessoa, então a foto não é dela para usar.",
			tr: "Profilin bu kişiye ait olduğu kanıtlanmadı, bu yüzden fotoğraf onun değil.",
			"zh-Hans": "无法确认该资料属于此人，因此其照片不能用作此人的照片。",
		},
		noStore: {
			en: "This install has no BLOB_READ_WRITE_TOKEN, so there is nowhere to keep a copy. Retrying will not help.",
			de: "Diese Installation hat kein BLOB_READ_WRITE_TOKEN, also gibt es keinen Ort für eine Kopie. Ein neuer Versuch hilft nicht.",
			es: "Esta instalación no tiene BLOB_READ_WRITE_TOKEN, así que no hay dónde guardar una copia. Reintentar no servirá.",
			fr: "Cette installation n'a pas de BLOB_READ_WRITE_TOKEN, il n'y a donc nulle part où garder une copie. Réessayer n'y changera rien.",
			"pt-BR":
				"Esta instalação não tem BLOB_READ_WRITE_TOKEN, então não há onde guardar uma cópia. Tentar de novo não vai ajudar.",
			tr: "Bu kurulumda BLOB_READ_WRITE_TOKEN yok, bu yüzden kopyayı saklayacak bir yer yok. Yeniden denemek işe yaramaz.",
			"zh-Hans":
				"此安装没有 BLOB_READ_WRITE_TOKEN，因此无处保存副本。重试也没有用。",
		},
		noStoreExpiring: {
			en: "This install has no BLOB_READ_WRITE_TOKEN, so there is nowhere to keep a copy. The source URL expires within weeks and is never stored. Retrying will not help.",
			de: "Diese Installation hat kein BLOB_READ_WRITE_TOKEN, also gibt es keinen Ort für eine Kopie. Die Quelladresse läuft in wenigen Wochen ab und wird nie gespeichert. Ein neuer Versuch hilft nicht.",
			es: "Esta instalación no tiene BLOB_READ_WRITE_TOKEN, así que no hay dónde guardar una copia. La URL de origen caduca en pocas semanas y nunca se guarda. Reintentar no servirá.",
			fr: "Cette installation n'a pas de BLOB_READ_WRITE_TOKEN, il n'y a donc nulle part où garder une copie. L'URL source expire en quelques semaines et n'est jamais enregistrée. Réessayer n'y changera rien.",
			"pt-BR":
				"Esta instalação não tem BLOB_READ_WRITE_TOKEN, então não há onde guardar uma cópia. A URL de origem expira em poucas semanas e nunca é salva. Tentar de novo não vai ajudar.",
			tr: "Bu kurulumda BLOB_READ_WRITE_TOKEN yok, bu yüzden kopyayı saklayacak bir yer yok. Kaynak adresin süresi birkaç hafta içinde dolar ve hiç saklanmaz. Yeniden denemek işe yaramaz.",
			"zh-Hans":
				"此安装没有 BLOB_READ_WRITE_TOKEN，因此无处保存副本。源地址几周内就会失效，且从不保存。重试也没有用。",
		},
		noContact: {
			en: "No such contact.",
			de: "Diesen Kontakt gibt es nicht.",
			es: "Ese contacto no existe.",
			fr: "Ce contact n'existe pas.",
			"pt-BR": "Esse contato não existe.",
			tr: "Böyle bir kişi yok.",
			"zh-Hans": "没有这个联系人。",
		},
		hasPhoto: {
			en: "They already have a photo.",
			de: "Es gibt schon ein Foto.",
			es: "Ya tiene una foto.",
			fr: "Il y a déjà une photo.",
			"pt-BR": "Já existe uma foto.",
			tr: "Zaten bir fotoğrafı var.",
			"zh-Hans": "已经有照片了。",
		},
		fetchFailed: {
			en: "The photo could not be fetched. The record is unchanged.",
			de: "Das Foto konnte nicht geladen werden. Der Datensatz ist unverändert.",
			es: "No se pudo descargar la foto. El registro no ha cambiado.",
			fr: "La photo n'a pas pu être récupérée. La fiche est inchangée.",
			"pt-BR": "Não foi possível baixar a foto. O registro não mudou.",
			tr: "Fotoğraf alınamadı. Kayıt değişmedi.",
			"zh-Hans": "无法获取照片。记录未更改。",
		},
		unchanged: {
			en: "Unchanged.",
			de: "Unverändert.",
			es: "Sin cambios.",
			fr: "Inchangé.",
			"pt-BR": "Sem alterações.",
			tr: "Değişmedi.",
			"zh-Hans": "未更改。",
		},
		nothingPoints: {
			en: "Nothing on this contact points at a picture. The record carries no GitHub account.",
			de: "Nichts an diesem Kontakt verweist auf ein Bild. Der Datensatz hat kein GitHub-Konto.",
			es: "Nada en este contacto apunta a una imagen. El registro no tiene cuenta de GitHub.",
			fr: "Rien sur ce contact ne mène à une image. La fiche n'a pas de compte GitHub.",
			"pt-BR":
				"Nada neste contato aponta para uma imagem. O registro não tem conta do GitHub.",
			tr: "Bu kişide bir resme işaret eden hiçbir şey yok. Kayıtta GitHub hesabı yok.",
			"zh-Hans": "该联系人没有任何指向图片的信息。记录中没有 GitHub 账号。",
		},
		none: {
			en: "No picture found.",
			de: "Kein Bild gefunden.",
			es: "No se encontró ninguna imagen.",
			fr: "Aucune image trouvée.",
			"pt-BR": "Nenhuma imagem encontrada.",
			tr: "Resim bulunamadı.",
			"zh-Hans": "没有找到图片。",
		},
		stored: (source: string): Lines => ({
			en: `Picture stored from ${source}.`,
			de: `Bild aus ${source} gespeichert.`,
			es: `Imagen guardada desde ${source}.`,
			fr: `Image enregistrée depuis ${source}.`,
			"pt-BR": `Imagem salva a partir de ${source}.`,
			tr: `Resim ${source} kaynağından kaydedildi.`,
			"zh-Hans": `已从 ${source} 保存图片。`,
		}),
	},

	webhooks: {
		unreadable: {
			en: "The queued webhook delivery is unreadable.",
			de: "Die eingereihte Webhook-Zustellung ist nicht lesbar.",
			es: "El envío de webhook en cola no se puede leer.",
			fr: "L'envoi de webhook en file d'attente est illisible.",
			"pt-BR": "A entrega de webhook na fila está ilegível.",
			tr: "Sıradaki webhook teslimatı okunamıyor.",
			"zh-Hans": "排队中的 webhook 投递无法读取。",
		},
		gone: {
			en: "The webhook is gone.",
			de: "Der Webhook ist weg.",
			es: "El webhook ya no existe.",
			fr: "Le webhook n'existe plus.",
			"pt-BR": "O webhook não existe mais.",
			tr: "Webhook artık yok.",
			"zh-Hans": "该 webhook 已不存在。",
		},
		off: {
			en: "The webhook is switched off.",
			de: "Der Webhook ist ausgeschaltet.",
			es: "El webhook está desactivado.",
			fr: "Le webhook est désactivé.",
			"pt-BR": "O webhook está desligado.",
			tr: "Webhook kapalı.",
			"zh-Hans": "该 webhook 已关闭。",
		},
		answered: (status: number): Lines => ({
			en: `The receiver answered ${status}.`,
			de: `Der Empfänger hat mit ${status} geantwortet.`,
			es: `El receptor respondió ${status}.`,
			fr: `Le destinataire a répondu ${status}.`,
			"pt-BR": `O receptor respondeu ${status}.`,
			tr: `Alıcı ${status} ile yanıt verdi.`,
			"zh-Hans": `接收方返回了 ${status}。`,
		}),
		gaveUp: (attempts: number, reason: string): Lines => ({
			en: `Gave up after ${attempts} attempts: ${reason}`,
			de: `Nach ${attempts} Versuchen aufgegeben: ${reason}`,
			es: `Abandonado tras ${attempts} intentos: ${reason}`,
			fr: `Abandonné après ${attempts} tentatives : ${reason}`,
			"pt-BR": `Desistiu após ${attempts} tentativas: ${reason}`,
			tr: `${attempts} denemeden sonra vazgeçildi: ${reason}`,
			"zh-Hans": `尝试 ${attempts} 次后放弃：${reason}`,
		}),
		secretUnreadable: {
			en: "The stored secret cannot be read. Enter it again.",
			de: "Das gespeicherte Geheimnis ist nicht lesbar. Gib es erneut ein.",
			es: "No se puede leer el secreto guardado. Introdúcelo de nuevo.",
			fr: "Le secret enregistré est illisible. Saisis-le à nouveau.",
			"pt-BR": "Não é possível ler o segredo salvo. Digite-o de novo.",
			tr: "Kayıtlı gizli anahtar okunamıyor. Yeniden gir.",
			"zh-Hans": "无法读取已保存的密钥。请重新输入。",
		},
		noAnswer: {
			en: "The receiver did not answer in time.",
			de: "Der Empfänger hat nicht rechtzeitig geantwortet.",
			es: "El receptor no respondió a tiempo.",
			fr: "Le destinataire n'a pas répondu à temps.",
			"pt-BR": "O receptor não respondeu a tempo.",
			tr: "Alıcı zamanında yanıt vermedi.",
			"zh-Hans": "接收方没有及时响应。",
		},
		noAnswerOrPrivate: {
			en: "The receiver did not answer in time, or its address is not a public one.",
			de: "Der Empfänger hat nicht rechtzeitig geantwortet, oder seine Adresse ist nicht öffentlich.",
			es: "El receptor no respondió a tiempo o su dirección no es pública.",
			fr: "Le destinataire n'a pas répondu à temps, ou son adresse n'est pas publique.",
			"pt-BR":
				"O receptor não respondeu a tempo, ou o endereço dele não é público.",
			tr: "Alıcı zamanında yanıt vermedi ya da adresi herkese açık değil.",
			"zh-Hans": "接收方没有及时响应，或者其地址不是公开地址。",
		},
	},

	slack: {
		notConnected: {
			en: "Slack is not connected.",
			de: "Slack ist nicht verbunden.",
			es: "Slack no está conectado.",
			fr: "Slack n'est pas connecté.",
			"pt-BR": "O Slack não está conectado.",
			tr: "Slack bağlı değil.",
			"zh-Hans": "Slack 未连接。",
		},
		noChannel: {
			en: "No such channel.",
			de: "Diesen Kanal gibt es nicht.",
			es: "Ese canal no existe.",
			fr: "Ce canal n'existe pas.",
			"pt-BR": "Esse canal não existe.",
			tr: "Böyle bir kanal yok.",
			"zh-Hans": "没有这个频道。",
		},
		noJoinGrant: {
			en: "This workspace did not grant Reloop permission to add itself to a private channel.",
			de: "Dieser Arbeitsbereich hat Reloop nicht erlaubt, sich selbst zu einem privaten Kanal hinzuzufügen.",
			es: "Este espacio de trabajo no dio permiso a Reloop para unirse a un canal privado.",
			fr: "Cet espace de travail n'a pas autorisé Reloop à s'ajouter à un canal privé.",
			"pt-BR":
				"Este espaço de trabalho não deu permissão ao Reloop para entrar em um canal privado.",
			tr: "Bu çalışma alanı Reloop'a kendini özel bir kanala ekleme izni vermedi.",
			"zh-Hans": "此工作区没有授权 Reloop 将自己加入私有频道。",
		},
		noCreateGrant: {
			en: "This workspace did not grant Reloop permission to create a private channel.",
			de: "Dieser Arbeitsbereich hat Reloop nicht erlaubt, einen privaten Kanal anzulegen.",
			es: "Este espacio de trabajo no dio permiso a Reloop para crear un canal privado.",
			fr: "Cet espace de travail n'a pas autorisé Reloop à créer un canal privé.",
			"pt-BR":
				"Este espaço de trabalho não deu permissão ao Reloop para criar um canal privado.",
			tr: "Bu çalışma alanı Reloop'a özel kanal oluşturma izni vermedi.",
			"zh-Hans": "此工作区没有授权 Reloop 创建私有频道。",
		},
		notVisible: {
			en: "Slack cannot see this channel. A member has to invite Reloop.",
			de: "Slack sieht diesen Kanal nicht. Ein Mitglied muss Reloop einladen.",
			es: "Slack no puede ver este canal. Un miembro tiene que invitar a Reloop.",
			fr: "Slack ne voit pas ce canal. Un membre doit inviter Reloop.",
			"pt-BR":
				"O Slack não consegue ver este canal. Um membro precisa convidar o Reloop.",
			tr: "Slack bu kanalı göremiyor. Bir üyenin Reloop'u davet etmesi gerekiyor.",
			"zh-Hans": "Slack 看不到这个频道。需要有成员邀请 Reloop。",
		},
		archived: {
			en: "This channel is archived. Somebody has to unarchive it before Reloop can join.",
			de: "Dieser Kanal ist archiviert. Jemand muss ihn wiederherstellen, bevor Reloop beitreten kann.",
			es: "Este canal está archivado. Alguien tiene que desarchivarlo antes de que Reloop pueda unirse.",
			fr: "Ce canal est archivé. Quelqu'un doit le désarchiver avant que Reloop puisse le rejoindre.",
			"pt-BR":
				"Este canal está arquivado. Alguém precisa desarquivá-lo antes que o Reloop possa entrar.",
			tr: "Bu kanal arşivlendi. Reloop katılmadan önce birinin arşivden çıkarması gerekiyor.",
			"zh-Hans": "此频道已归档。需要有人先取消归档，Reloop 才能加入。",
		},
		missingScope: {
			en: "Slack refused: a permission is missing. Reconnect Slack.",
			de: "Slack hat abgelehnt: Eine Berechtigung fehlt. Verbinde Slack neu.",
			es: "Slack lo rechazó: falta un permiso. Vuelve a conectar Slack.",
			fr: "Slack a refusé : une autorisation manque. Reconnecte Slack.",
			"pt-BR": "O Slack recusou: falta uma permissão. Reconecte o Slack.",
			tr: "Slack reddetti: bir izin eksik. Slack'i yeniden bağla.",
			"zh-Hans": "Slack 拒绝了：缺少一项权限。请重新连接 Slack。",
		},
		reconnect: {
			en: "Slack needs to be reconnected.",
			de: "Slack muss neu verbunden werden.",
			es: "Hay que volver a conectar Slack.",
			fr: "Slack doit être reconnecté.",
			"pt-BR": "O Slack precisa ser reconectado.",
			tr: "Slack'in yeniden bağlanması gerekiyor.",
			"zh-Hans": "需要重新连接 Slack。",
		},
		unknownBot: {
			en: "Slack did not report which user Reloop is.",
			de: "Slack hat nicht gemeldet, welcher Nutzer Reloop ist.",
			es: "Slack no indicó qué usuario es Reloop.",
			fr: "Slack n'a pas indiqué quel utilisateur est Reloop.",
			"pt-BR": "O Slack não informou qual usuário é o Reloop.",
			tr: "Slack, Reloop'un hangi kullanıcı olduğunu bildirmedi.",
			"zh-Hans": "Slack 没有说明 Reloop 是哪个用户。",
		},
		refused: (error: string): Lines => ({
			en: `Slack refused the request (${error}).`,
			de: `Slack hat die Anfrage abgelehnt (${error}).`,
			es: `Slack rechazó la solicitud (${error}).`,
			fr: `Slack a refusé la demande (${error}).`,
			"pt-BR": `O Slack recusou a solicitação (${error}).`,
			tr: `Slack isteği reddetti (${error}).`,
			"zh-Hans": `Slack 拒绝了该请求（${error}）。`,
		}),
		unreadable: {
			en: "Slack sent back something unreadable.",
			de: "Slack hat etwas Unlesbares zurückgeschickt.",
			es: "Slack devolvió algo ilegible.",
			fr: "Slack a renvoyé une réponse illisible.",
			"pt-BR": "O Slack devolveu algo ilegível.",
			tr: "Slack okunamayan bir yanıt gönderdi.",
			"zh-Hans": "Slack 返回了无法读取的内容。",
		},
		alreadyIn: (channel: string): Lines => ({
			en: `Reloop was already in #${channel}.`,
			de: `Reloop war schon in #${channel}.`,
			es: `Reloop ya estaba en #${channel}.`,
			fr: `Reloop était déjà dans #${channel}.`,
			"pt-BR": `O Reloop já estava em #${channel}.`,
			tr: `Reloop zaten #${channel} kanalındaydı.`,
			"zh-Hans": `Reloop 已经在 #${channel} 中。`,
		}),
		joined: (channel: string): Lines => ({
			en: `Reloop joined #${channel}.`,
			de: `Reloop ist #${channel} beigetreten.`,
			es: `Reloop se unió a #${channel}.`,
			fr: `Reloop a rejoint #${channel}.`,
			"pt-BR": `O Reloop entrou em #${channel}.`,
			tr: `Reloop #${channel} kanalına katıldı.`,
			"zh-Hans": `Reloop 已加入 #${channel}。`,
		}),
		couldNotJoin: (channel: string, reason: string): Lines => ({
			en: `Reloop could not join #${channel}. ${reason}`,
			de: `Reloop konnte #${channel} nicht beitreten. ${reason}`,
			es: `Reloop no pudo unirse a #${channel}. ${reason}`,
			fr: `Reloop n'a pas pu rejoindre #${channel}. ${reason}`,
			"pt-BR": `O Reloop não conseguiu entrar em #${channel}. ${reason}`,
			tr: `Reloop #${channel} kanalına katılamadı. ${reason}`,
			"zh-Hans": `Reloop 无法加入 #${channel}。${reason}`,
		}),
		matched: (members: number, channels: number): Lines => ({
			en: `Matched ${members} workspace ${members === 1 ? "member" : "members"} by email and found ${channels} available ${channels === 1 ? "channel" : "channels"}.`,
			de: `${members} ${members === 1 ? "Mitglied" : "Mitglieder"} des Arbeitsbereichs per E-Mail zugeordnet und ${channels} ${channels === 1 ? "verfügbaren Kanal" : "verfügbare Kanäle"} gefunden.`,
			es: `${members} ${members === 1 ? "miembro" : "miembros"} del espacio de trabajo asociados por correo y ${channels} ${channels === 1 ? "canal disponible" : "canales disponibles"} encontrados.`,
			fr: `${members} ${members === 1 ? "membre" : "membres"} de l'espace de travail associés par e-mail et ${channels} ${channels === 1 ? "canal disponible trouvé" : "canaux disponibles trouvés"}.`,
			"pt-BR": `${members} ${members === 1 ? "membro" : "membros"} do espaço de trabalho associados por e-mail e ${channels} ${channels === 1 ? "canal disponível encontrado" : "canais disponíveis encontrados"}.`,
			tr: `Çalışma alanından ${members} üye e-posta ile eşleştirildi ve ${channels} kullanılabilir kanal bulundu.`,
			"zh-Hans": `已按邮箱匹配 ${members} 名工作区成员，并找到 ${channels} 个可用频道。`,
		}),
	},
} as const;
